from meep.materials import cSi, aSi, ITO, Al2O3, Al2O3_aniso, AlN, AlN_aniso, BK7, fused_quartz, GaAs, Si3N4, Si3N4_VISNIR, Si3N4_NIR, SiN, Ag, Ag_visible, Au, Au_JC_visible, Au_visible, Cu, Al, Al_visible, Al_drude, Be, Cr, Cr_visible, Ni, Pd, Pt, Ti, Ti_visible, Ti_drude, W, Co, Mo, NiCr, NiFe, SiO2, InP, Ge, Si, PMMA, PC, PS, CLS, BaB2O4, LiNbO3, CaWO4, CaCO3, SiO2_aniso, GaN, Y2O3, YAG, CdTe
import meep as mp

# 定义复杂的材料数据
MATERIAL_DATABASE = {
    "c-Si": cSi,
    "a-Si": aSi,
    "ITO": ITO,
    "Al2O3": Al2O3,
    "Al2O3 (anisotropic)": Al2O3_aniso,
    "AlN": AlN,
    "AlN (anisotropic)": AlN_aniso,
    "BK7": BK7,
    "fused quartz": fused_quartz,
    "GaAs":GaAs,
    "Si3N4":Si3N4,
    "Si3N4 (Philipp)":Si3N4_VISNIR,
    "Si3N4 (Luke)":Si3N4_NIR,
    "Silicon nitride": SiN,
    "Silver":Ag,
    "Ag visible": Ag_visible,
    "Gold":Au,
    "Gold JC visible":Au_JC_visible,
    "Gold visible": Au_visible,
    "Copper":Cu,
    "Aluminium":Al,
    "Aluminium visible": Al_visible,
    "Aluminium drude":Al_drude,
    "Beryllium":Be,
    "Chromium":Cr,
    "Chromium visible":Cr_visible,
    "Nickel":Ni,
    "Palladium":Pd,
    "Platinum":Pt,
    "Titanium":Ti,
    "Titanium visible":Ti_visible,
    "Titanium drude":Ti_drude,
    "Tungsten":W,
    "Cobalt":Co,
    "Molybdenum":Mo,
    "Nickel chrome":NiCr,
    "Nickel iron":NiFe,
    "Silicon dioxide":SiO2,
    "Indium phosphide":InP,
    "Germanium":Ge,
    "Silicon":Si,
    "PMMA":PMMA,
    "Polycarbonate":PC,
    "Polystyrene":PS,
    "Cellulose":CLS,
    "Barium borate": BaB2O4,
    "Lithium niobate":LiNbO3,
    "Calcium tungstate":CaWO4,
    "Calcium carbonate":CaCO3,
    "Silicon dioxide(anisotropic)":SiO2_aniso,
    "Gallium nitride":GaN,
    "Yttrium oxide":Y2O3,
    "Yttrium aluminum garnet":YAG,
    "Cadmium telluride":CdTe,
}

def get_material(name):
    """安全获取材料的接口"""
    return MATERIAL_DATABASE.get(name, mp.Medium(index=1.0)) # 默认返回空气